# Generated by Django 3.2.3 on 2023-03-09 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='partyHistoryStudy',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('metting_theme', models.CharField(max_length=255, verbose_name='会议主题')),
                ('meeting_time', models.DateField(verbose_name='会议时间')),
                ('meeting_place', models.CharField(max_length=255, verbose_name='会议地点')),
                ('number_participants', models.IntegerField(verbose_name='参会人数')),
                ('class_name', models.CharField(max_length=255, verbose_name='班级名称')),
                ('college_name', models.CharField(max_length=255, verbose_name='学院')),
                ('grade', models.IntegerField(verbose_name='年级')),
                ('metting_images', models.ImageField(upload_to='images/tasks/party_history_study', verbose_name='会议图片')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '党史学习记录表',
                'verbose_name_plural': '党史学习记录表',
                'db_table': 'party_history_study',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
