# Generated by Django 3.2.3 on 2023-03-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_history_study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyhistorystudy',
            name='metting_images',
            field=models.CharField(help_text='会议图片', max_length=255, verbose_name='会议图片'),
        ),
    ]
