# Generated by Django 3.2.3 on 2023-03-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_history_study', '0002_alter_partyhistorystudy_metting_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyhistorystudy',
            name='meeting_time',
            field=models.DateTimeField(verbose_name='会议时间'),
        ),
    ]
