# Generated by Django 3.2.3 on 2023-05-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_history_study', '0004_partyhistorystudy_audit_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partyhistorystudy',
            old_name='metting_theme',
            new_name='meeting_theme',
        ),
    ]
